hostname: DX-LAP-01
keyboard_layout: "0813:00000813"
secondary_keyboard: "0409:00000409"
display_scaling: 150
desktop_background: "#000000"
wallpaper_disabled: true
timezone: UTC
driver_mode: windows_update